apiVersion: apps/v1
kind: Deployment
metadata:
  name: valsea-coding-challenge
  labels:
    app: valsea-coding-challenge
spec:
    replicas: 1
    selector:
        matchLabels:
          app: valsea-coding-challenge
    template:
        metadata:
          labels:
              app: valsea-coding-challenge
        spec:
          containers:
          - name: valsea-coding-challenge
            image: valsea_coding_challenge:latest
            ports:
            - containerPort: 8080
            env:
              - name: PORT
                value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: valsea-coding-challenge
spec:
    selector:
        app: valsea-coding-challenge
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
    type: LoadBalancer
